/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.AlumnoDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import modelo.Alumno;

/**
 *
 * @author guvad
 */
public class JFrameBajas extends javax.swing.JFrame {

    /**
     * Creates new form JFrameBajas
     */
    public JFrameBajas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bajaCajaNumControl = new javax.swing.JTextField();
        BajaButtonBuscar = new javax.swing.JButton();
        bajaButtonBorrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        bajaCajaNombres = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bajaCajaApPaterno = new javax.swing.JTextField();
        bajaButtonEliminar = new javax.swing.JButton();
        bajaButtonCancelar = new javax.swing.JButton();
        bajaCajaApMaterno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bajaSpinnerEdad = new javax.swing.JSpinner();
        bajaSpinnerSemestre = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bajaComboCarrera = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        bajaTabla = new javax.swing.JTable();
        mensaje = new javax.swing.JLabel();

        setTitle("BAJAS ALUMNOS");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BAJAS ALUMNOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setText("NUMERO DE CONTROL:");

        bajaCajaNumControl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bajaCajaNumControlKeyTyped(evt);
            }
        });

        BajaButtonBuscar.setText("BUSCAR");
        BajaButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajaButtonBuscarActionPerformed(evt);
            }
        });

        bajaButtonBorrar.setText("BORRAR");
        bajaButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaButtonBorrarActionPerformed(evt);
            }
        });

        jLabel11.setText("NOMBRES:");

        bajaCajaNombres.setEnabled(false);

        jLabel12.setText("APELLIDO PATERNO:");

        bajaCajaApPaterno.setEnabled(false);

        bajaButtonEliminar.setText("ELIMINAR");
        bajaButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaButtonEliminarActionPerformed(evt);
            }
        });

        bajaButtonCancelar.setText("CANCELAR");
        bajaButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaButtonCancelarActionPerformed(evt);
            }
        });

        bajaCajaApMaterno.setEnabled(false);

        jLabel13.setText("APELLIDO MATERNO:");

        jLabel14.setText("EDAD:");

        bajaSpinnerEdad.setEnabled(false);

        bajaSpinnerSemestre.setEnabled(false);

        jLabel15.setText("SEMESTRE:");

        jLabel16.setText("CARRERA:");

        bajaComboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion...", "ISC", "IM", "IIA", "LC", "LA" }));
        bajaComboCarrera.setEnabled(false);

        bajaTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(bajaTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bajaCajaApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bajaCajaNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BajaButtonBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bajaCajaNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bajaCajaApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(bajaSpinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(bajaComboCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(bajaSpinnerSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bajaButtonEliminar)
                            .addComponent(bajaButtonCancelar)
                            .addComponent(bajaButtonBorrar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(mensaje)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(bajaCajaNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bajaButtonBorrar)
                    .addComponent(BajaButtonBuscar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(mensaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(bajaCajaNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(bajaCajaApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(bajaButtonEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(bajaCajaApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bajaButtonCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(bajaSpinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(bajaSpinnerSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(bajaComboCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bajaButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaButtonBorrarActionPerformed
        bajaCajaNumControl.setText("");
        bajaCajaNombres.setText("");
        bajaCajaApPaterno.setText("");
        bajaCajaApMaterno.setText("");
        bajaSpinnerEdad.setValue(0);
        bajaSpinnerSemestre.setValue(0);
        bajaComboCarrera.setSelectedIndex(0);
       
    }//GEN-LAST:event_bajaButtonBorrarActionPerformed

    private void bajaButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaButtonEliminarActionPerformed
         eliminarAlumno();
    }//GEN-LAST:event_bajaButtonEliminarActionPerformed

    private void bajaButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaButtonCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_bajaButtonCancelarActionPerformed

    private void BajaButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajaButtonBuscarActionPerformed
        buscarAlumno(mensaje,bajaCajaNumControl,bajaCajaNombres,bajaCajaApPaterno,bajaCajaApMaterno,bajaSpinnerEdad,bajaSpinnerSemestre,bajaComboCarrera);
    }//GEN-LAST:event_BajaButtonBuscarActionPerformed

    private void bajaCajaNumControlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bajaCajaNumControlKeyTyped
         char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isDigit(car)){
        }else{
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_bajaCajaNumControlKeyTyped
public void buscarAlumno(JLabel mensaje,JTextField cajaNumControl,JTextField cajaNombres,JTextField cajaApPaterno, JTextField cajaApMaterno,JSpinner spinnerEdad, JSpinner spinnerSemestre, JComboBox comboCarrera) {
		AlumnoDAO aDAO=new AlumnoDAO();
		Alumno alumno= aDAO.buscarAlumno(cajaNumControl.getText());
		if(alumno!=null) {
			mensaje.setText("");
			cajaNombres.setText(alumno.getNombre());
			cajaApPaterno.setText(alumno.getPrimerAp());
			cajaApMaterno.setText(alumno.getSegundoAp());
                        spinnerEdad.setValue(alumno.getEdad());
			spinnerSemestre.setValue(alumno.getSemetre());
			comboCarrera.setSelectedItem(alumno.getCarrera());
			
			
		}else{
                    mensaje.setText("<html> <p style=\"color:red;\">ESE ALUMNO NO EXISTE</p></html>");
                }
	}
public void eliminarAlumno() {
		AlumnoDAO alumnoDAO=new AlumnoDAO();
		if(alumnoDAO.eliminarAlumnos(bajaCajaNumControl.getText())) {
			mensaje.setText("<html> <p style=\"color:blue;\">SE ELIMINO ALUMNO</p></html>");
                    try {
                        actualizarTabla(bajaTabla);
                    } catch (SQLException ex) {
                        Logger.getLogger(JFrameBajas.class.getName()).log(Level.SEVERE, null, ex);
                    }
		}
		else
			mensaje.setText("<html> <p style=\"color:red;\">NO SE PUDO ELIMINAR ALUMNO</p></html>");
	}
public static void actualizarTabla(JTable tabla) throws SQLException {
    	String controlador="com.mysql.cj.jdbc.Driver";
    	String url="jdbc:mysql://localhost/BD_Escuela?useTimezone=true&serverTimezone=UTC";
    	String consulta="SELECT * FROM alumnos";
    	ResultSetTableModel modeloDatos=null;
		 try {
			modeloDatos= new ResultSetTableModel(controlador, url, consulta);
		 } catch (ClassNotFoundException e) {
			  e.printStackTrace();
		    } catch (SQLException e) {
		    	e.printStackTrace();
		     }
		 tabla.setModel(modeloDatos);
	  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameBajas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BajaButtonBuscar;
    private javax.swing.JButton bajaButtonBorrar;
    private javax.swing.JButton bajaButtonCancelar;
    private javax.swing.JButton bajaButtonEliminar;
    private javax.swing.JTextField bajaCajaApMaterno;
    private javax.swing.JTextField bajaCajaApPaterno;
    private javax.swing.JTextField bajaCajaNombres;
    private javax.swing.JTextField bajaCajaNumControl;
    private javax.swing.JComboBox<String> bajaComboCarrera;
    private javax.swing.JSpinner bajaSpinnerEdad;
    private javax.swing.JSpinner bajaSpinnerSemestre;
    public javax.swing.JTable bajaTabla;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mensaje;
    // End of variables declaration//GEN-END:variables
}
