/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.AlumnoDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import modelo.Alumno;

/**
 *
 * @author guvad
 */
public class JInternalFrameAltas extends javax.swing.JInternalFrame {

    /** Creates new form JInternalFrameAltas */
    public JInternalFrameAltas() {
        try {
            initComponents();
            actualizarTabla(altaTabla);
        } catch (SQLException ex) {
            Logger.getLogger(JInternalFrameAltas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        altaCajaNumControl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        altaCajaNombres = new javax.swing.JTextField();
        altaCajaApPaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        altaCajaApMaterno = new javax.swing.JTextField();
        altaSpinnerEdad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        altaSpinnerSemestre = new javax.swing.JSpinner();
        altaComboCarrera = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        altaTabla = new javax.swing.JTable();
        altasButtonAgregar = new javax.swing.JButton();
        altasButtonBorrar = new javax.swing.JButton();
        altasButtonCancelar = new javax.swing.JButton();
        altaMensaje = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Altas");

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALTAS ALUMNOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        altaCajaNumControl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                altaCajaNumControlKeyTyped(evt);
            }
        });

        jLabel2.setText("NUMERO DE CONTROL:");

        jLabel3.setText("NOMBRES:");

        altaCajaNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaCajaNombresActionPerformed(evt);
            }
        });
        altaCajaNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                altaCajaNombresKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                altaCajaNombresKeyTyped(evt);
            }
        });

        altaCajaApPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                altaCajaApPaternoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                altaCajaApPaternoKeyTyped(evt);
            }
        });

        jLabel4.setText("APELLIDO PATERNO:");

        jLabel5.setText("APELLIDO MATERNO:");

        altaCajaApMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                altaCajaApMaternoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                altaCajaApMaternoKeyTyped(evt);
            }
        });

        jLabel6.setText("EDAD:");

        jLabel7.setText("SEMESTRE:");

        altaComboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion...", "ISC", "IM", "IIA", "LC", "LA" }));

        jLabel8.setText("CARRERA:");

        altaTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(altaTabla);

        altasButtonAgregar.setText("AGREGAR");
        altasButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altasButtonAgregarActionPerformed(evt);
            }
        });

        altasButtonBorrar.setText("BORRAR");
        altasButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altasButtonBorrarActionPerformed(evt);
            }
        });

        altasButtonCancelar.setText("CANCELAR");
        altasButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altasButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(altaMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(altaComboCarrera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(altaSpinnerSemestre))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(altaSpinnerEdad))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(altaCajaApPaterno))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(altaCajaNombres))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(altaCajaNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(2, 2, 2)
                                    .addComponent(altaCajaApMaterno)))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(altasButtonAgregar)
                                .addComponent(altasButtonBorrar)
                                .addComponent(altasButtonCancelar))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(altaMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(altaCajaNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(altasButtonAgregar)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(altaCajaNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(altaCajaApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(altasButtonBorrar))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(altaCajaApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(altaSpinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(altaSpinnerSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(altasButtonCancelar)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(altaComboCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaCajaNumControlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_altaCajaNumControlKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isDigit(car)){
        }else{
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_altaCajaNumControlKeyTyped

    private void altaCajaNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaCajaNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_altaCajaNombresActionPerformed

    private void altaCajaNombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_altaCajaNombresKeyReleased
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isDigit(car) || car==' '){
        }else{
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_altaCajaNombresKeyReleased

    private void altaCajaNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_altaCajaNombresKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isDigit(car) || car==' '){
        }else{
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_altaCajaNombresKeyTyped

    private void altaCajaApPaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_altaCajaApPaternoKeyReleased
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isDigit(car) || car==' '){
        }else{
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_altaCajaApPaternoKeyReleased

    private void altaCajaApPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_altaCajaApPaternoKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isDigit(car) || car==' '){
        }else{
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_altaCajaApPaternoKeyTyped

    private void altaCajaApMaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_altaCajaApMaternoKeyReleased
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isDigit(car) || car==' '){
        }else{
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_altaCajaApMaternoKeyReleased

    private void altaCajaApMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_altaCajaApMaternoKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isDigit(car) || car==' '){
        }else{
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_altaCajaApMaternoKeyTyped

    private void altasButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altasButtonAgregarActionPerformed
        try {
            altaAlumno();
        } catch (SQLException ex) {
            Logger.getLogger(JInternalFrameAltas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_altasButtonAgregarActionPerformed

    private void altasButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altasButtonBorrarActionPerformed
        altaCajaNumControl.setText("");
        altaCajaNombres.setText("");
        altaCajaApPaterno.setText("");
        altaCajaApMaterno.setText("");
        altaSpinnerEdad.setValue(0);
        altaSpinnerSemestre.setValue(0);
        altaComboCarrera.setSelectedIndex(0);
        altaMensaje.setText("");
    }//GEN-LAST:event_altasButtonBorrarActionPerformed

    private void altasButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altasButtonCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_altasButtonCancelarActionPerformed
public static void actualizarTabla(JTable tabla) throws SQLException {
    	String controlador="com.mysql.cj.jdbc.Driver";
    	String url="jdbc:mysql://localhost/BD_Escuela?useTimezone=true&serverTimezone=UTC";
    	String consulta="SELECT * FROM alumnos";
    	ResultSetTableModel modeloDatos=null;
		 try {
			modeloDatos= new ResultSetTableModel(controlador, url, consulta);
		 } catch (ClassNotFoundException e) {
			  e.printStackTrace();
		    } catch (SQLException e) {
		    	e.printStackTrace();
		     }
		 tabla.setModel(modeloDatos);
	  }


  public boolean validacionEspaciosVacios(JComponent ...componentes) {
	boolean esVacio=false;
	for (JComponent c : componentes) {
	if(c instanceof JTextField) {
            if (((JTextField) c).getText().replaceAll(" ","").equals("")) 
            	esVacio= true;
	}
               
	if(c instanceof JComboBox) {
	    if(((JComboBox) c).getSelectedItem().toString().equals("Selecciona una opcion..."))
	        esVacio= true;
	    }
        
        if(c instanceof JSpinner) {
            if((Integer)((JSpinner)c).getValue()<=0){
                esVacio=true;
            }
		}
	    
	}
        return esVacio;
  }
  
  
    public void altaAlumno() throws SQLException {
		if(validacionEspaciosVacios(altaCajaNumControl,altaCajaNombres,altaCajaApPaterno,altaCajaApMaterno,altaSpinnerEdad,altaSpinnerSemestre,altaComboCarrera)){
                    JOptionPane.showMessageDialog(getContentPane(), "Favor de llenar todos los campos!","Atención", JOptionPane.WARNING_MESSAGE);
                }else{
        Alumno alumno=new Alumno();
		AlumnoDAO alumnoDAO=new AlumnoDAO();
	        alumno.setNumControl(altaCajaNumControl.getText());
		alumno.setNombre(altaCajaNombres.getText());
		alumno.setPrimerAp(altaCajaApPaterno.getText());
		alumno.setSegundoAp(altaCajaApMaterno.getText());
                alumno.setEdad((byte)Integer.parseInt(altaSpinnerEdad.getValue().toString()));
	        alumno.setSemetre((byte)Integer.parseInt(altaSpinnerSemestre.getValue().toString()));
		alumno.setCarrera(altaComboCarrera.getSelectedItem().toString());
		Alumno alumno2= alumnoDAO.buscarAlumno(altaCajaNumControl.getText());
		if(alumno2!=null) {
			altaMensaje.setText("<html> <p style=\"color:red;\">NO SE PUDO REALIZAR EL ALTA, ESE ALUMNO YA EXISTE</p></html>");
		}else {
		if(alumnoDAO.agregarAlumno(alumno)) 
			altaMensaje.setText("<html> <p style=\"color:blue;\">ALTA REALIZADA CORRECTAMENTE</p></html>");
		else
			altaMensaje.setText("<html> <p style=\"color:red;\">NO SE PUDO REALIZAR EL ALTA</p></html>");
		actualizarTabla(altaTabla);
	   }
                }
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altaCajaApMaterno;
    private javax.swing.JTextField altaCajaApPaterno;
    private javax.swing.JTextField altaCajaNombres;
    private javax.swing.JTextField altaCajaNumControl;
    private javax.swing.JComboBox<String> altaComboCarrera;
    private javax.swing.JLabel altaMensaje;
    private javax.swing.JSpinner altaSpinnerEdad;
    private javax.swing.JSpinner altaSpinnerSemestre;
    public javax.swing.JTable altaTabla;
    private javax.swing.JButton altasButtonAgregar;
    private javax.swing.JButton altasButtonBorrar;
    private javax.swing.JButton altasButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
